# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        django-version: ["2.2", "3.2", "4.0", "dev"]
        mode: ["flake8", "flake8-strict", "docs", "tests"]

    steps:
    - uses: actions/checkout@v2
    - name: Install OS dependencies
      run: |
        sudo apt install -y binutils libproj-dev gdal-bin libsqlite3-mod-spatialite

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel virtualenv tox coveralls
    - name: Erase cached coverage
      run: |
        coverage erase
    - name: Test with pytest
      run: |
        tox -e py${{matrix.python-version}}-${{matrix.django-version}}-${{matrix.mode}}
        